# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-11 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='BuyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='Carfirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm', models.CharField(max_length=32, verbose_name='商品厂商')),
            ],
        ),
        migrations.CreateModel(
            name='CarInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carname', models.CharField(max_length=32, verbose_name='汽车名称')),
                ('carsell', models.CharField(max_length=32, verbose_name='车主姓名')),
                ('carphone', models.CharField(max_length=32, verbose_name='车主电话')),
                ('carsize', models.CharField(max_length=32, verbose_name='车辆价格')),
                ('carbetter', models.CharField(max_length=32, verbose_name='优惠信息')),
                ('carother', models.CharField(default=None, max_length=32, verbose_name='其他信息')),
                ('catstatus', models.CharField(default='待支付', max_length=32, verbose_name='成交状态')),
                ('carfirm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Carfirm', verbose_name='所属经销商')),
            ],
        ),
        migrations.CreateModel(
            name='Cartype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32, verbose_name='商品类别')),
            ],
        ),
        migrations.CreateModel(
            name='OrderManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carname', models.CharField(max_length=32, verbose_name='汽车名称')),
                ('carstatus', models.CharField(max_length=32, verbose_name='订单状态')),
            ],
        ),
        migrations.CreateModel(
            name='SellUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='UserManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('usertype', models.IntegerField(choices=[(1, '买家'), (2, '卖家')], verbose_name='用户类型')),
            ],
        ),
        migrations.AddField(
            model_name='carinfo',
            name='cartype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Cartype', verbose_name='所属类别'),
        ),
    ]
