# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-12 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20190411_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanager',
            name='usertype',
            field=models.CharField(max_length=32, verbose_name='用户类型'),
        ),
    ]
