# Generated by Django 2.0.2 on 2019-04-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20190412_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinfo',
            name='carage',
            field=models.CharField(default=None, max_length=32, verbose_name='车辆车龄'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='carother',
            field=models.CharField(max_length=32, verbose_name='车辆里程'),
        ),
    ]
